{% set name = "frozenlist" %}
{% set version = "1.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/frozenlist-{{ version }}.tar.gz
  sha256: 58bcc55721e8a90b88332d6cd441261ebb22342e238296bb330968952fbb3a6a

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - frozenlist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/frozenlist
  summary: A list-like structure which implements collections.abc.MutableSequence
  description: A list-like structure which implements collections.abc.MutableSequence
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/aio-libs/frozenlist
  doc_url: https://frozenlist.aio-libs.org/

extra:
  recipe-maintainers:
    - cbouss
