{% set name = "frozenlist" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/frozenlist-{{ version }}.tar.gz
  sha256: 3ede829ed8d842f6cd48fc7081d7a41001a56f1f38603f9d49bf3020d59a31ad

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - cython
    - expandvars
    - pip
    - setuptools>=47
    - tomli  # [py<311]
    - wheel
  run:
    - python

test:
  imports:
    - frozenlist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/aio-libs/frozenlist
  summary: A list-like structure which implements collections.abc.MutableSequence
  description: A list-like structure which implements collections.abc.MutableSequence
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/aio-libs/frozenlist
  doc_url: https://frozenlist.aio-libs.org/

extra:
  recipe-maintainers:
    - cbouss
